((nil . ((indent-tabs-mode . nil)
         (fill-column . 80)))
 (go-mode . (
             (indent-tabs-mode . t)
             (tab-width . 4)
             ))
 (web-mode . ((indent-tabs-mode . nil)
              (web-mode-style-padding . 0)
              (web-mode-script-padding . 0)
              (web-mode-indent-style . 2)
              (web-mode-markup-indent-offset . 2)
              (web-mode-css-indent-offset . 2)
              (web-mode-code-indent-offset . 2)))
)
